name: Deploy to Azure VM

on:
  push:
    branches:
      - feat/impl-service-ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Copy files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.VM_USERNAME }}/food-classifier"
          
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # create environment variable file (600 permission)
            umask 077
            cat > /etc/food-classifier/.env << 'EOL'
            AZURE_CUSTOM_VISION_ENDPOINT="${{ secrets.AZURE_CUSTOM_VISION_ENDPOINT }}"
            AZURE_CUSTOM_VISION_API_KEY="${{ secrets.AZURE_CUSTOM_VISION_API_KEY }}"
            AZURE_CUSTOM_VISION_PROJECT_ID="${{ secrets.AZURE_CUSTOM_VISION_PROJECT_ID }}"
            AZURE_CUSTOM_VISION_MODEL_NAME="${{ secrets.AZURE_CUSTOM_VISION_MODEL_NAME }}"
            EOL
            
            cd ~/food-classifier
            
            # create virtual environment
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # service restart
            sudo systemctl restart food-classifier